In [17]:
import numpy as np
print(np.__version__)         # show numpy version
#print(np.show_config())      # show numpy build configuration

1.19.2


In [23]:
# Creating array through list
arr1 = np.array([2,3,5,7,9])
arr1

array([2, 3, 5, 7, 9])

In [24]:
# Creating array through tuple
arr2 = np.array((1,2,3,4,5))
arr2

array([1, 2, 3, 4, 5])

In [6]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

In [25]:
# Create 2 dimensional array     # Need to use 2 square brackets to get them consider as 2d array bcz it is list of list
arr3 = np.array([[1,2],[3,4]])
arr3

array([[1, 2],
       [3, 4]])

In [26]:
# Create 2 dimensional array through list
mylist = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [28]:
arr3 = np.array(mylist)
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [29]:
# Create 2 dimensional array through tuple
tuplearray = np.array([(1,2,3),(4,5,6),(7,8,9),(10,11,12)])
tuplearray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
# Performing mathematical Operation on Array. This is not possibile on list.
arr1/2

array([1. , 1.5, 2.5, 3.5, 4.5])

In [30]:
# change array datatype to complex
arr4 = np.array([1,2,3,4], dtype=complex)
arr4


array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [31]:
# change array datatype to bool
arr4 = np.array([1,0,3,0], dtype=bool)
arr4


array([ True, False,  True, False])

In [34]:
# change array datatype to complex, another way to do it
arr5 = np.array([1,2,3,4], "complex")
arr5


array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [33]:
# Upcast example - Change from integer to float incase of int and float data types use togther...this is called upcast
arr6 = np.array([1,2,3,4.0])
arr6

array([1., 2., 3., 4.])

In [35]:
# Upcast Example  --- int to float
arr7 = np.array([1,2.0,3,4])
arr7

array([1., 2., 3., 4.])

In [37]:
# Upcast Example  ----int, float to complex
arr7 = np.array([1,2.0,3,4,1.+0.j])
arr7

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 1.+0.j])

In [38]:
# Error with String
arr6 = np.array([1,2,3,4.0,'NA'])
arr6

array(['1', '2', '3', '4.0', 'NA'], dtype='<U32')

In [39]:
arr6.dtype

dtype('<U32')

In [40]:
#Example of change array datatype to float
arr8 = np.array([1,2,3,4], dtype=float)
arr8

array([1., 2., 3., 4.])

In [41]:
#Minimum dimensions 2:
arr8 = np.array([1,2,3,4], ndmin=2)
arr8


array([[1, 2, 3, 4]])

## Arange 

In [10]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [42]:
# Arange function - "Creates array of evenly spaced values"

# Create an array starts from 1, end at 9(excluding 9)
arr9 = np.arange(1,9)
arr9

array([1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
# Create an array starts from 1, end at 9(excluding 9) and step 2 
arr9 = np.arange(1,9,2)
arr9

array([1, 3, 5, 7])

In [44]:
# Create an array without giving start number, start and step are optional   ----Integer
arr10 = np.arange(5)
arr10

array([0, 1, 2, 3, 4])

In [45]:
# Create an array without giving start number, start and step are optional    ------float
arr10 = np.arange(5.0)
arr10

array([0., 1., 2., 3., 4.])

In [46]:
# if we are giving step then start is must
arr11 = np.arange(1,10,2)
arr11

array([1, 3, 5, 7, 9])

In [6]:
arr12 = np.arange(1,10,2,dtype=float)    
print(arr12)

# Can simple write "float" also instead of dtype=float but it will work with complete inputs like start, stop and end inputs
# It will not work with only stop input
arr12 = np.arange(1,10,2,"float")
print(arr12)

[1. 3. 5. 7. 9.]
[1. 3. 5. 7. 9.]


In [48]:
arr12 = np.arange(1.0,10,2)    
arr12

array([1., 3., 5., 7., 9.])

In [49]:
# Create array by using arange of complex data  type 
arr13 = np.arange(20,dtype=complex)
arr13

array([ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,
        7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j,
       14.+0.j, 15.+0.j, 16.+0.j, 17.+0.j, 18.+0.j, 19.+0.j])

In [7]:
arr13 = np.arange(2,20,4,dtype=complex)
arr13

array([ 2.+0.j,  6.+0.j, 10.+0.j, 14.+0.j, 18.+0.j])

## Zeros

In [50]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [25]:
# Create an array by using zeros function -----default data type is float

# Zero function create array filled with zero
arr14 = np.zeros(5)
arr14

array([0., 0., 0., 0., 0.])

In [29]:
# Create an array by using zeros function -----datatype change to int
arr15 = np.zeros(5, "int")
arr15

array([0, 0, 0, 0, 0])

In [35]:
#Create a 2d array with 2 rows and 3 columns by using zeros function
arr16 = np.zeros((2,3))
arr16

# We can use [ ] brackets also
arr16 = np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

## Ones

In [41]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [36]:
# Create an array using ones function ---- default data type is float
# Ones function create array filled with ones

arr17 = np.ones(5)
arr17

array([1., 1., 1., 1., 1.])

In [40]:
# change data type to int
arr18 = np.ones(5,dtype = int)
arr18

array([1, 1, 1, 1, 1])

In [19]:
# change data type to int
arr18 = np.ones(5,"complex")
arr18

array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j])

In [33]:
# Create an array of 5 Rows and 4 Columns using ones function
arr18 = np.ones((5,4))
arr18

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
arr18.ndim


2

In [42]:
help(np.empty)

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of uninitialized (arbitrary) data of the given shape, dtype, and
        order.  Object arrays will be initialized to None.
    
    See Also
    --------
    empty_like : Return an empty array with shape and type of input.
    ones : Return a new array setting values to one.
    zeros : Return a new array 

In [50]:
arr19 = np.empty(5)
arr19

array([1., 1., 1., 1., 1.])

In [47]:
arr20 = np.empty([2,3],dtype=int)
arr20

array([[-1001683344,         460,           0],
       [          0,           1,           0]])

## linspace

In [51]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [8]:
# linspace function - "Creates array filled evenly spaced values"   - here bydefault dtype is float
arr21 = np.linspace(1,100,num=5)
arr21

# difference is 100-1/5-1 = 24.75

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [20]:
arr21 = np.linspace(1,100,num=5,retstep = True)
arr21

(array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ]), 24.75)

In [10]:
# linspace function - "Creates array filled evenly spaced values"
arr21 = np.linspace(1,100,num=5,dtype=int)
arr21

# difference is 100-1/5-1 = 24.75

array([  1,  25,  50,  75, 100])

In [56]:
# linspace function by using endpoint, bydefault its True
arr22 = np.linspace(1,100,num=5,endpoint=False,dtype=int)
arr22

(array([ 1, 20, 40, 60, 80]), 19.8)

In [59]:
# Linspace function by using retstep, bydefault its False
arr23 = np.linspace(1,100,num=4,retstep=True)
arr23

(array([  1.,  34.,  67., 100.]), 33.0)

In [60]:
# Linspace function ...without giving num parameter.......bydefault num paramerter value is 50
arr24 = np.linspace(1,10)
arr24

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

## Identity Matirx : Eye and Identity

In [63]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
    See Also
    -

In [65]:
# Eye() Function - Returns array filled with zeros except in the K-th diagonal whose values are equal to 1

arr25 = np.eye(5)   # same as arr25 = np.eye(5,5) 
arr25

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [66]:
arr25 = np.eye(2,3)
arr25

array([[1., 0., 0.],
       [0., 1., 0.]])

In [21]:
arr25 = np.eye(5,k=1)
arr25

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [22]:
arr25 = np.eye(5,k=3)
arr25

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [71]:
arr25 = np.eye(5,k=-1)
arr25

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [23]:
arr25 = np.eye(5,k=-2)
arr25

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [72]:
arr25 = np.eye(5,k=2)
arr25

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [74]:
arr25 = np.eye(5,dtype=int)
arr25

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [75]:
help(np.identity)

Help on function identity in module numpy:

identity(n, dtype=None)
    Return the identity array.
    
    The identity array is a square array with ones on
    the main diagonal.
    
    Parameters
    ----------
    n : int
        Number of rows (and columns) in `n` x `n` output.
    dtype : data-type, optional
        Data-type of the output.  Defaults to ``float``.
    
    Returns
    -------
    out : ndarray
        `n` x `n` array with its main diagonal set to one,
        and all other elements 0.
    
    Examples
    --------
    >>> np.identity(3)
    array([[1.,  0.,  0.],
           [0.,  1.,  0.],
           [0.,  0.,  1.]])



In [77]:
arr26 = np.identity(5)
arr26

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
arr26 = np.identity(5,dtype=int)
arr26

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## Full

In [9]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C')
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar or array_like
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of `fill_value` with the given shape, dtype, and order.
    
    See Also
    --------
    full_like : Return a new array with shape of input filled with value.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    zeros : Return a new array set

In [27]:
arrfull = np.full((2,3),4.5)
arrfull

array([[4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5]])

In [30]:
# Create an array by using full 
arrfull = np.full(arr26.shape,4)     # here we reference shape of arr26
arrfull

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [32]:
# Create an array by using full_like
arrfull = np.full_like(arr26,4)    # here we use full_like and given ref of an array instead of its shape
arrfull

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

__Takeaways__<br>
- __numpy.linspace()__ returns __evenly spaced numbers__ over a specified interval<br>
- __numpy.eye__ is used to generate an __identity matrix__<br>
- __numpy.zeros__ generates a matrix with all elements __0__.<br>
- __numpy.ones__ generates a matrix with all elements __1__.<br>
- __numpy.full__ generates a matrix with __given value__.<br>
So, as you can see there are many built in function in numpy each faciliating performing vaious mathematical operations on different types of data.

## Random

Array Initialization using Random Numbers

Here we are going to see how to populate array with random numbers.<br>


In [80]:
help(np.random)

Help on package numpy.random in numpy:

NAME
    numpy.random

DESCRIPTION
    Random Number Generation
    
    Use ``default_rng()`` to create a `Generator` and call its methods.
    
    =============== =========================================================
    Generator
    --------------- ---------------------------------------------------------
    Generator       Class implementing all of the random number distributions
    default_rng     Default constructor for ``Generator``
    =============== =========================================================
    
    ============================================= ===
    BitGenerator Streams that work with Generator
    --------------------------------------------- ---
    MT19937
    PCG64
    Philox
    SFC64
    ============================================= ===
    
    ============================================= ===
    Getting entropy to initialize a BitGenerator
    --------------------------------------------- ---
    Seed

In [81]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

In [39]:
arr27 = np.random.rand(5)      # uniformly distributed values
arr27

array([0.09335467, 0.64946102, 0.27464066, 0.08143701, 0.00247015])

In [85]:
arr27 = np.random.rand(4,5)
arr27

array([[0.92855076, 0.79516916, 0.40020268, 0.31433847, 0.59002114],
       [0.36855671, 0.42268277, 0.89753649, 0.94848989, 0.0790871 ],
       [0.08384778, 0.29553429, 0.60339704, 0.87983077, 0.14691024],
       [0.92912099, 0.65179115, 0.26076661, 0.62861363, 0.53873834]])

Generate a 4*4 matrix where the elements are distributed in random distribition.

In [43]:
# normally distributed values

arr27 = np.random.randn(4,4)           # Standard Normal where mean = 0 and SD = 1
arr27
# In Output all of these values are Z Values and all of them are Standard Normal

array([[-1.14477847, -1.2933187 , -1.1437275 , -0.05755809],
       [ 0.99557266,  1.77812327,  1.46277212,  1.65757078],
       [ 1.47605092, -1.39124714,  0.72099138, -0.32424119],
       [-2.01530183,  0.97132876, -0.83973341, -1.72990493]])

In [47]:
# Standard Normal -> mu = 2 and SD = 3        
#---> z = (x- mean)/SD   
#= Z * SD + mean = x

arr27 = np.random.randn(4,4) * 3 + 2
arr27


array([[ 1.82691891, -0.7814355 ,  1.83550336,  2.33676895],
       [-1.85366918,  1.22920738,  0.43949554, -0.67727807],
       [-0.49481236,  1.69155093,  1.52698304,  4.92925781],
       [ 3.96352445,  7.05554689, -0.31307186,  4.64201354]])

In [63]:
arr28 = 2 + np.random.randn(4,4) * 3
arr28

array([[ 3.27587605,  0.30805976, -0.51071912,  2.8767962 ],
       [ 3.13164421, -2.0147851 ,  3.05910603, -2.94369683],
       [ 3.17979812, -0.52992706,  8.06618871,  2.11887158],
       [ 0.96794855, -0.3531642 ,  7.22786569, -0.08199247]])

In [48]:
# Create a 3d array by using random.rand
arr28 = np.random.rand(4,2,3)
arr28

array([[[0.47070529, 0.79185193, 0.11242456],
        [0.5032625 , 0.14994886, 0.31487883]],

       [[0.47786585, 0.57409367, 0.1769222 ],
        [0.75773938, 0.55990864, 0.30631294]],

       [[0.4845213 , 0.7979944 , 0.50105387],
        [0.59804146, 0.62661179, 0.36019211]],

       [[0.06226242, 0.97934016, 0.62651575],
        [0.74763782, 0.09373985, 0.92414307]]])

In [50]:
# Create an array through random and by using shape --- this will be created through np.random.sample instead of np.random.rand

arr28 = np.random.sample(arr26.shape)
arr28


array([[0.62571725, 0.87351535, 0.19969336, 0.32350277, 0.99287026],
       [0.52495233, 0.67669225, 0.45039349, 0.23706292, 0.25494157],
       [0.4787718 , 0.41799847, 0.33280214, 0.09408791, 0.56590609],
       [0.01753069, 0.40889131, 0.74862422, 0.85063323, 0.30904564],
       [0.69881717, 0.81466159, 0.16129498, 0.70012213, 0.14397442]])

In [10]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [55]:
# Random integer values                   # uniformly distributed integers in a given range
np.random.randint(7,size=(3,2))           # start with 0 and ends with 7-1

array([[4, 4],
       [5, 4],
       [4, 0]])

In [62]:
# Random integer values
np.random.randint(2,7,size=(3,2))        # start with 2 and ends with 7-1

array([[5, 5],
       [2, 3],
       [4, 3]])

In [52]:
# Random integer values                 # start with 3 and ends with 9-1
np.random.randint(3,9,(3,3))

array([[4, 6, 7],
       [3, 4, 6],
       [4, 3, 4]])

In [25]:
# Generate a random array of 9 elements and convert it to 3*3 matrix using reshape
Nine_elements_random = np.random.rand(9)
print(Nine_elements_random)

Nine_elements_random.reshape(3,3)

[0.37776617 0.46622088 0.94390264 0.34676645 0.50643953 0.51838589
 0.56184716 0.57165749 0.35565795]


array([[0.37776617, 0.46622088, 0.94390264],
       [0.34676645, 0.50643953, 0.51838589],
       [0.56184716, 0.57165749, 0.35565795]])

In [8]:
Nine_elements_random

array([0.39536089, 0.58867271, 0.43588673, 0.94599439, 0.08652687,
       0.65536818, 0.52092799, 0.25811908, 0.75508486])

## Attributes of Array

In [100]:
# Attributes of Array
arr1.ndim

1

In [103]:
arr26.ndim

2

In [104]:
arr1.shape

(5,)

In [105]:
arr26.shape

(5, 5)

In [3]:
arr30 = np.zeros((2,3,4))
arr30

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [110]:
arr30.shape

(2, 3, 4)

In [111]:
arr26.size

25

In [112]:
arr1.size


5

In [113]:
arr30.size

24

In [114]:
arr1.dtype

dtype('int32')

In [115]:
arr26.dtype

dtype('int32')

In [117]:
arr30.dtype

dtype('float64')

In [41]:
arr30 = np.array([1,2,'NA'])
arr30.dtype

dtype('<U11')

In [118]:
arr30.itemsize

8

In [119]:
arr26.itemsize

4

In [128]:
x=np.int16(arr30)
x.dtype

dtype('int16')

In [4]:
arr30.astype(int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [5]:
arr30

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [66]:
arr31 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]], [[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
arr31

                

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [89]:

arr31[1][:,2]

array([15, 19, 23])

## Numpy - Array Indexing and Slicing

In [134]:
# Fetch 12 from above array
# one way to fetch 12

arr31[0][2][3]

12

In [7]:
#Another way to fetch same number 12
arr31[0,2,3]

12

In [18]:
# Fetch 2nd column from second matrix
arr31[1][:,1:2]


array([[14],
       [18],
       [22]])

In [10]:
arr31[1,:,1:2]

array([[14],
       [18],
       [22]])

In [77]:
arr31[1][:,-3]

array([14, 18, 22])

In [13]:
arr31[1][:,::2]

array([[13, 15],
       [17, 19],
       [21, 23]])

In [11]:
arr31[1,:,::2]

array([[13, 15],
       [17, 19],
       [21, 23]])

In [81]:
arr31[1][:,1::2]

array([[14, 16],
       [18, 20],
       [22, 24]])

In [12]:
arr31[1,:,1::2]

array([[14, 16],
       [18, 20],
       [22, 24]])

In [201]:
# access 1st column of both the 2D's
arr31[:,:,:1]

array([[[ 1],
        [ 5],
        [ 9]],

       [[13],
        [17],
        [21]]])

In [203]:
arr31[:,1:,::2]

array([[[ 5,  7],
        [ 9, 11]],

       [[17, 19],
        [21, 23]]])

In [88]:
# access second row of 1st 2d array
arr31[0][1]

array([5, 6, 7, 8])

In [14]:
arr31[1][:,2]

array([15, 19, 23])

In [90]:
arr32 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr32

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [186]:
arr32[:,2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [185]:
arr32[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [91]:
# Access 6,7,10,11
arr32[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [92]:
# Access 2,3,6,7
arr32[:2,1:3]

array([[2, 3],
       [6, 7]])

In [94]:
myarr = np.arange(6,95)
myarr

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
       57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
       74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
       91, 92, 93, 94])

In [68]:
myarr.shape


(89,)

In [67]:
myarr.size

89

In [69]:
myarr[88]

94

In [70]:
myarr[0:5] = 5     # Refer as broadcasting.......can't do this with List but can do with Arrays
myarr

array([ 5,  5,  5,  5,  5, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
       57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
       74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
       91, 92, 93, 94])

In [71]:
np.bincount(myarr)

array([0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [3]:
 arr = np.array([0, 5, 5, 0, 2, 4, 3, 0, 0, 5, 4, 1, 9, 9])
 np.bincount(arr)  

array([4, 1, 1, 1, 2, 3, 0, 0, 0, 2], dtype=int64)

In [98]:
# Repeat an array 3 times
arr = np.array([1,2,3])
rep = np.repeat(arr,3)
print(rep)


[1 1 1 2 2 2 3 3 3]


array([3, 6, 9])

In [14]:
# Repeat an array 
arr = np.array([[1,2,3]])
rep = np.repeat(arr,3,axis=0)      # Here axis = 0 is for Rows and axis=1 is for columns 
print(rep)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [108]:
'''Create array like this
array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])'''
dummy = np.ones((5,5),dtype=int)
dummy[1:-1,1:-1]=0
dummy[2,2]=9
dummy

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [49]:
'''Create array like this
array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])'''
      
arr33=np.ones((5,5), dtype =int)
print(arr33)
print("--------------------")
print("--------------------")
arr33[1:4,1:4]=0
print(arr33)
print("--------------------")
print("--------------------")
arr33[2,2]=9
print(arr33)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
--------------------
--------------------
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
--------------------
--------------------
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [60]:
# Second solution for above problem
'''
Create array like this
array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])
'''
      
arr33=np.ones((5,5), dtype =int)
print(arr33)
print("--------------------")
print("--------------------")
arr34 = np.zeros((3,3),dtype=int)
arr34[1,1]=9
print(arr34)

print("--------------------")
print("--------------------")
arr33[1:4,1:4]= arr34
print(arr33)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
--------------------
--------------------
[[0 0 0]
 [0 9 0]
 [0 0 0]]
--------------------
--------------------
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [17]:
# Third solution for above problem

arr33=np.ones((5,5), dtype =int)
arr33[1:4,1:4]=0
arr33[2,2]=9
arr33

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

##### Be Careful when copying arrays !!!

In [38]:
a = np.array([2,3,4])
b = a
print(b)
b[0]=20
print(a)

[2 3 4]
[20  3  4]


In [39]:
a = np.array([2,3,4])
b = a.copy()
print(b)
b[0]=20
print(a)
print(b)

[2 3 4]
[2 3 4]
[20  3  4]


##### Mathematics !!!

In [40]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [169]:
# Using Scaler

In [67]:
a * 2

array([ 2,  4,  6,  8, 10])

In [70]:
a + 2         # can be written like this np.add(a,2)

array([3, 4, 5, 6, 7])

In [71]:
a - 2         # can be written like this np.subtract(a,2)

array([-1,  0,  1,  2,  3])

In [72]:
a ** 2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [ ]:
'''
Perform Arithmetic operations on arrays

a + b            np.add(a,b)
a - b            np.subtract(a,b)
a * b            np.multiply(a,b)
a / b            np.divide(a,b)
a % b            np.mod(a,b)
a ** b           np.power(a,b)
'''

In [171]:
b = np.array([1,0,1,0,1])
b


array([1, 0, 1, 0, 1])

In [75]:
a + b

array([2, 2, 4, 4, 6])

In [143]:
np.add(a,b)

array([2, 2, 4, 4, 6])

In [154]:
np.add(a,2)

array([3, 4, 5, 6, 7])

In [144]:
np.subtract(a,b)

array([0, 2, 2, 4, 4])

In [146]:
a1 = np.arange(1,7).reshape(2,3)
a1


array([[1, 2, 3],
       [4, 5, 6]])

In [147]:
b1 = np.arange(7,13).reshape(2,3)
b1


array([[ 7,  8,  9],
       [10, 11, 12]])

In [150]:
print(a1 + b1)
print()
print()
print(np.add(a1,b1))

[[ 8 10 12]
 [14 16 18]]


[[ 8 10 12]
 [14 16 18]]


In [153]:
print(b1/a1)

[[7.  4.  3. ]
 [2.5 2.2 2. ]]


In [160]:
a3 = np.array([[1,2],[3,4],[5,6]])
a3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [161]:
b3 = np.array([10,20])
b3

array([10, 20])

In [162]:
a3 + b3

array([[11, 22],
       [13, 24],
       [15, 26]])

## Multiplication

In [36]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])
                   

In [14]:
m1

array([[1, 2],
       [3, 4]])

In [15]:
m2

array([[5, 6],
       [7, 8]])

In [16]:
m1*m2       # This is array multiplication, not the matrix multiplication

array([[ 5, 12],
       [21, 32]])

In [37]:
np.multiply(m1,m2)

array([[ 5, 12],
       [21, 32]])

### Use dot funciton for Matrix multiplication


In [173]:
m1.dot(m2)            # Matrix multiplication using dot function on arrays

array([[19, 22],
       [43, 50]])

In [174]:
np.dot(m1,m2)        # Matrix multiplication using dot function on arrays

array([[19, 22],
       [43, 50]])

In [110]:
arr_cond = np.arange(2,15)
arr_cond

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [112]:
arr_cond[[2,4,5]]

array([4, 6, 7])

## Matrix Creation, Addition, Multiplication and Transpose

In [190]:
help(np.matrix)

Help on class matrix in module numpy:

class matrix(ndarray)
 |  matrix(data, dtype=None, copy=True)
 |  
 |  matrix(data, dtype=None, copy=True)
 |  
 |  .. note:: It is no longer recommended to use this class, even for linear
 |            algebra. Instead use regular arrays. The class may be removed
 |            in the future.
 |  
 |  Returns a matrix from an array-like object, or from a string of data.
 |  A matrix is a specialized 2-D array that retains its 2-D nature
 |  through operations.  It has certain special operators, such as ``*``
 |  (matrix multiplication) and ``**`` (matrix power).
 |  
 |  Parameters
 |  ----------
 |  data : array_like or string
 |     If `data` is a string, it is interpreted as a matrix with commas
 |     or spaces separating columns, and semicolons separating rows.
 |  dtype : data-type
 |     Data-type of the output matrix.
 |  copy : bool
 |     If `data` is already an `ndarray`, then this flag determines
 |     whether the data is copied (the 

In [189]:
# Matrix can be created using string notation
# Matrix objects are always 2d, it can't be 3d or 4d using Matrix class but ndarrays are multi dimensional 
# Can use * for matrix multiplicaton
# It is no longer recommended to use this class, even for linear algebra. Instead use regular arrays. This class may be removed in futures


In [188]:

mat = np.matrix("1 2 ; 3 4")
mat

matrix([[1, 2],
        [3, 4]])

In [180]:
# Create matrix from the list
mat1 = np.matrix([[10,20],[30,40]])
mat1

matrix([[10, 20],
        [30, 40]])

In [182]:
# Create matrix from the array
mat2 = np.matrix(m1)
mat2

matrix([[1, 2],
        [3, 4]])

In [184]:
# Matrix Addition
madd = mat1 + mat2
madd

matrix([[11, 22],
        [33, 44]])

In [185]:
# Matrix Multiplication
mmult = mat1 * mat2
mmult

matrix([[ 70, 100],
        [150, 220]])

In [187]:
# Transpose of a Matrix
mat1.T

matrix([[10, 30],
        [20, 40]])

### Numpy Broadcasting
Broadcasting is used to describe how arrays are treated during mathematical operations.
The term broadcast is used because a small array is stretched or *broadcasted* over a larger array so that they have compatible sizes.

** Broadcasting Rules: **
Starting from the last axis and working backwards, Numpy compares the array dimensions:
* If two dimensions are __equal__, you can __continue__     (Size of each dimension should be same)
* If one of the __operand is 1__, __stretch__ it to match the largest one     (Size of one of the dimension should be 1)
* When one of the __shapes run out of dimension__ (because it has less dimensions than the other shape), Numpy will __assign 1__ in the comparision process until the other shape's dimensions run out as well. 


In [113]:
arr_2d = np.array([[1,2,3],[5,6,7],[8,9,10],[12,13,14]])    # Creating numpy array
arr_2d

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [12, 13, 14]])

In [114]:
arr_2d.shape

(4, 3)

In [119]:
scaler = 3                                                  # scaler

In [120]:
scaler

3

In [121]:
arr_2d +  3                                            # operation with a scaler

array([[ 4,  5,  6],
       [ 8,  9, 10],
       [11, 12, 13],
       [15, 16, 17]])

arr_2d --> 4 * 3

scaler --> 1 * 1<br>
Here the scaler is stretched and is added to all elements of the array. 

In [123]:
arr_1d = np.array([10,10,10])                               # array with different shape
arr_1d.shape

(3,)

In [124]:
print(arr_1d)
print()
print()
print(arr_2d)

[10 10 10]


[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]
 [12 13 14]]


In [125]:
arr_2d + arr_1d                           # operation with a array of different shape

array([[11, 12, 13],
       [15, 16, 17],
       [18, 19, 20],
       [22, 23, 24]])

arr_2d --> 4 * 3

arr_1d --> 1 * 3
In this case the array with lower dimension i.e. arr_1d is stretched such that it matches the dimensions of arr_2d
And then addition is performed. Lets learn it better with one diagramatic example.

** Example of Image Broadcasting **
<img src="https://github.com/insaid2018/Term-1/blob/master/Images/broadcasting.png?raw=true">


From the above image you can see how and when the data is stretched to carry out the mathematical operations. Here we have performed addition on arrays of varying dimensions. Always Remember to stretch the data as per the broadcasting rules.

** Now lets look at a different shape of array. **

In [126]:
# arr --> 1 * 4
arr = np.array([[1,1,1,1]])


In [127]:
print(arr)
print()
print()
print(arr_2d)
arr_2d.shape

[[1 1 1 1]]


[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]
 [12 13 14]]


(4, 3)

In [128]:
arr_2d + arr

ValueError: operands could not be broadcast together with shapes (4,3) (1,4) 

**If the dimensions do not match it will throw an exception**

__Takeaways__<br>
Keep a note of the __shape or dimension of the arrays__ before applying any mathematical operation and make sure they satisfy the _Numpy broadcasting rules_ else value error may occur.

### Numpy Mathematical Functions
Here you can see a lot of commonly used built-in functions of numpy for mathematical operations.
These functions are faster and optimized for large size arrays.

In [130]:
stats = np.array([[1,2,3],[6,5,4]])
stats


array([[1, 2, 3],
       [6, 5, 4]])

In [97]:
np.min(stats)              # Minimum value of array

1

In [132]:
np.max(stats)              # Maximum value of array

6

In [131]:
stats.min()

1

In [62]:
stats.max()

6

In [133]:
a=np.arange(2,11)
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [134]:
min(a)

2

In [135]:
# minimum in first row in 2d array
np.min(stats[0:])


1

In [136]:
# minimum in second row in 2d array
np.min(stats[1:])

4

In [137]:
# minimum in third column in 2d array
np.min(stats[:,2])

3

In [138]:
# maximum in second column in 2d array
np.max(stats[:,1])

5

In [20]:
stats

array([[1, 2, 3],
       [6, 5, 4]])

In [61]:
np.min(stats, axis = 0)  # Axis 0 means Checking min in rows

array([1, 2, 3])

In [98]:
np.min(stats, axis = 1)  # Axis 1 means Checking min in columns

array([1, 4])

In [94]:
np.max(stats)

6

In [41]:
stats = np.array([[1,2,3],[6,5,4]])
stats


array([[1, 2, 3],
       [6, 5, 4]])

In [100]:
np.max(stats, axis = 0)  # Axis 0 means Checking max in rows

array([4, 5, 6])

In [3]:
stats = np.array([[1,2,3],[6,5,4]])
stats


array([[1, 2, 3],
       [6, 5, 4]])

In [99]:
np.max(stats, axis = 1)  # Axis 1 means Checking max in columns

array([3, 6])

In [101]:
np.sum(stats)

21

In [88]:
np.sum(stats, axis=0)     # Axis 0 means sum of Rows

array([7, 7, 7])

In [89]:
np.sum(stats, axis=1)    # Axis 1 means sum of columns

array([ 6, 15])

In [139]:
stats.argmin()           # Index position of minimum of array

0

In [140]:
stats.argmax()           # Index position of maximum of array

3

In [7]:
np.argmin(stats)

0

In [ ]:
np.argmax(stats)

In [75]:
stats.mean()       # np.mean(stats)   -  # To calculate mean of all the values in an array

3.5

**Missing values** of a column can be replaced by the __mean__ of that column in some datasets

In [43]:
np.mean(stats, axis =1)

array([2., 5.])

In [21]:
np.median(stats)

3.5

In [78]:
np.sqrt(stats)     #  # To calculate square root of all elements in an array

array([[1.        , 1.41421356, 1.73205081],
       [2.44948974, 2.23606798, 2.        ]])

In [80]:
np.exp(stats)       # To calculate exponential value of each element in an array

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [403.42879349, 148.4131591 ,  54.59815003]])

__Takeaways__<br>
We have seen that Numpy have various methods to do various mathematical operations like:<br/>
- finding _minimum, maximum_,
- calulating _average values_,
- finding exponential value of each element of array.
There are more functions available to calculate various statistical parameters.

### Array Manipulation
Here we will see some numpy functions that can change the structure(shape) of an array.



### Change in Structure or Shape of Array


** Reshape Function **

In [141]:
np.arange(1,10).reshape(3,3)    # use of reshape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [142]:
before = np.array([[1,2,3,4,5],[6,7,8,9,19]])
print(before)
print("shape before is {}".format(before.shape))
print("-----------------------")
after = before.reshape(5,2)
print(after)
print("shape after is {}".format(after.shape))

[[ 1  2  3  4  5]
 [ 6  7  8  9 19]]
shape before is (2, 5)
-----------------------
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 19]]
shape after is (5, 2)


In [143]:
a=np.arange(1,13).reshape(4,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [144]:
# transform a matrix into a one-dimensional array.
a.flatten()                          # Flatten is used to convert a 2D/3D array to 1D array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [147]:
b = a.transpose()                 # Transpose is used to convert the rows into columns and vice-versa
b

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [151]:
np.transpose(b)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [150]:
b.T

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
# Resize an array     - resize(arr, new_shape) function returns a new array with the specified shape.
b=np.resize(a, (3,3))
print(b)
print("------------------")
c = np.resize(a, (5,2))
print(c)
print("------------------")
d = np.resize(a, (5,3))      # Incase If the new array is larger than the original array, then the new array is filled with repeated copies of array
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
------------------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [ 1  2  3]]


##### LInear Algebra

In [91]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [79]:
c = np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [80]:
# Find the Determinant # linalg - Linear Algebra
np.linalg.det(c)

1.0

In [77]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [78]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

### Inverse a Matrix

In [51]:
matrix = np.array([[1, 2],
                   [3, 4]])
# Calculate inverse of matrix
np.linalg.inv(matrix)



array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [52]:
matrix1 = np.array([[2, 3],
                   [4, 5]])
# Calculate inverse of matrix
np.linalg.inv(matrix1)

array([[-2.5,  1.5],
       [ 2. , -1. ]])

In [53]:
# Convert arr to a Python list
a = matrix.tolist()
print(a)
type(a)

[[1, 2], [3, 4]]


list

In [14]:
ab = np.array([[1,2,3],[4,5,6]])
print(type(ab))

abc = ab.tolist()
print(abc)
type(abc)

<class 'numpy.ndarray'>
[[1, 2, 3], [4, 5, 6]]


list

In [18]:
print(len(ab))
print(ab.ndim)
print(ab.dtype)

2
2
int32


In [45]:
len(matrix)   # is same as matrix.ndim which retunns dimension of matrix

2

In [7]:
# arr.size # Return number of elements in arr
# len(arr) #Length of array arr.ndim # Number of array dimension
# arr.dtype # Return type of elements in arr
# arr.dtype.name # Name of data type
# arr.astype(int) # Convert an array to a different type
# arr.astype(dtype) # Convert arr elements to type dtype
# np.info(np.eye) # View documentation for np.eye
# .tolist()  # to convert array to list

 eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0

Returns
-------
I : ndarray of shape (N,M)
  An array where all elements are equal to zero, except for the `k`-th
  diagonal, whose values are equal to one.

See Also
--------
identity : (almost) equivalent function
diag : diagonal 2-D array from a 1-D array specified by the user.

Examples
--------
>>> np.eye(2, dt

In [55]:
arr= np.arange(2,11)
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr>5

array([False, False, False, False,  True,  True,  True,  True,  True])

In [49]:
arr[arr>5]                      # Conditional 

array([ 6,  7,  8,  9, 10])

In [55]:
arr[arr!=5]                    # Conditional 
        

array([ 2,  3,  4,  6,  7,  8,  9, 10])

### Mergeing and Spliting Arrays 

In [52]:
# Concatenate 1d array
arra = np.arange(5)
print(arra)
print()
arrb = np.arange(10,20,2)
print(arrb)
print()
arrx = np.concatenate((arra, arrb))
arrx

[0 1 2 3 4]

[10 12 14 16 18]



array([ 0,  1,  2,  3,  4, 10, 12, 14, 16, 18])

In [54]:
arrc = np.arange(20,30,3)
arrc


array([20, 23, 26, 29])

In [55]:
np.concatenate((arra, arrb, arrc))

array([ 0,  1,  2,  3,  4, 10, 12, 14, 16, 18, 20, 23, 26, 29])

In [58]:
arrz = np.zeros(10)
arrz

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [59]:
np.concatenate((arra,arrb), out=arrz)   # Output is carried in arrz array but arrz array needs to be define first
arrz

array([ 0.,  1.,  2.,  3.,  4., 10., 12., 14., 16., 18.])

In [ ]:
# Concatenate 2d array

In [153]:
d1 = np.array([[1,2],[3,4]])
d2 = np.array([[5,6]])
np.concatenate((d1,d2))             # Here Axis by default 0

array([[1, 2],
       [3, 4],
       [5, 6]])

In [154]:
d2.T

array([[5],
       [6]])

In [84]:
# Concateneate with the help of Transpose......------    .T used for transpose of 2nd Matrix
np.concatenate((d1,d2.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [155]:
arr_x = np.array([1,2,3,4,5,6,7,8]).reshape(2,4)
arr_y = np.array([10,20,30,40,50,60,70,80]).reshape(2,4)


In [86]:
arr_x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [87]:
arr_y

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [13]:
np.concatenate((arr_x,arr_y))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 20, 30, 40],
       [50, 60, 70, 80]])

In [114]:
vz = np.concatenate((arr_x,arr_y), axis=0)
vz

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 20, 30, 40],
       [50, 60, 70, 80]])

In [115]:
hz = np.concatenate((arr_x,arr_y), axis=1)
hz

array([[ 1,  2,  3,  4, 10, 20, 30, 40],
       [ 5,  6,  7,  8, 50, 60, 70, 80]])

In [27]:
z = np.zeros((4,4))     

In [28]:
np.concatenate((arr_x,arr_y), out =z)   # Take concatenate output in z array 
z

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [10., 20., 30., 40.],
       [50., 60., 70., 80.]])

In [ ]:
# Vstack 1d array - Array must be of same shape and we will get 2d array as result
# Vstack 2d array - In 2d, 3d arrays, it behave same as concatenate function with axis =0
# Hstack 1d array - 1d array can be of any type and we will get 1d array as output
# Hstack 2d array - In 2d, 3d arrays, it behave same as concatenate function with axis = 1

In [156]:
np.vstack([arr_x,arr_y])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 20, 30, 40],
       [50, 60, 70, 80]])

In [160]:
np.hstack((arr_x,arr_y))

#np.vstack([arr_x,arr_y])

array([[ 1,  2,  3,  4, 10, 20, 30, 40],
       [ 5,  6,  7,  8, 50, 60, 70, 80]])

In [158]:
# Vertically Staking Vector
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [98]:
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [161]:
# Horizontal Stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print("------")
print(h2)
print("------")
np.hstack([h1,h2])

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
------
[[0. 0.]
 [0. 0.]]
------


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [8]:
h3 = np.zeros((2,4))       ## Array size should match for concatenate
h4 = np.ones((3,4))      
np.hstack([h3,h4])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

## Horizontal Split using hsplit**

In [90]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
# Split 1d array
np.split(a,3)                 # Split array into 3 parts, by default axis = 0

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [57]:

b=np.arange(1,13).reshape(6,2)
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [59]:
# Split 2d array
np.split(b,2)

[array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])]

In [105]:
c=np.arange(1,13).reshape(2,6)
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [116]:
vz

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 20, 30, 40],
       [50, 60, 70, 80]])

In [125]:
hs = np.hsplit(vz,2)      #  # hsplit Split the array along the axis =1 as bydefault axis =1
hs


[array([[ 1,  2],
        [ 5,  6],
        [10, 20],
        [50, 60]]),
 array([[ 3,  4],
        [ 7,  8],
        [30, 40],
        [70, 80]])]

In [126]:
# same output we can get though split also with axis =1
np.split(vz,2,axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [10, 20],
        [50, 60]]),
 array([[ 3,  4],
        [ 7,  8],
        [30, 40],
        [70, 80]])]

In [118]:
hz

array([[ 1,  2,  3,  4, 10, 20, 30, 40],
       [ 5,  6,  7,  8, 50, 60, 70, 80]])

In [120]:
vs = np.vsplit(hz,2)      # vsplit Split the array along the axis =0 as there is no parameter like Axis in Vsplit
vs

[array([[ 1,  2,  3,  4, 10, 20, 30, 40]]),
 array([[ 5,  6,  7,  8, 50, 60, 70, 80]])]

Vertical Splits can be used in **cross-validation in Machine Learning** <br>

__Takeaways__<br>
Using _concatenate_ function we can _merge_ arrays columnwise and rowwise. Also arrays can be horizontally and vertically spliited using _hsplit_ and _vsplit_.

## Advance Indexing

In [162]:
# Integer indexing in 1d array

b=np.arange(1,10)     # Fetch values of index 1, 4 & 5 
print(b)

index = np.array([1,4,5])    # Create an array on index and pass that index to fetch values from array
print(index)

b[index]

[1 2 3 4 5 6 7 8 9]
[1 4 5]


array([2, 5, 6])

In [136]:
# Access elements repeately in 1d array
b[[1,4,1,4,1,4]]

array([2, 5, 2, 5, 2, 5])

In [130]:
b[[1,4,5]]         # We can use list also instead of creating index array

array([2, 5, 6])

In [165]:
# Interger Indexing in 2d array
b = np.arange(1,10).reshape(3,3)
print(b)
# Access 3 and 7
print("\n")

b[[0,2],[2,0]]     # First [0,2] defines rows and second [2,0] defines columns



[[1 2 3]
 [4 5 6]
 [7 8 9]]




array([3, 7])

In [133]:
# Access 4, 6 & 7
b[[1,1,2],[0,2,0]]   # # First [1,1,2] defines rows and second [0,2,0] defines columns

array([4, 6, 7])

## Boolean Indexing

In [137]:
bi = np.array([[1,2,-2,4],[4,-3,-4,5]])
bi

array([[ 1,  2, -2,  4],
       [ 4, -3, -4,  5]])

In [138]:
bi[bi<0]

array([-2, -3, -4])

In [139]:
bi[bi>2]

array([4, 4, 5])

In [140]:
bi[bi>2]*5

array([20, 20, 25])

## Array Manipulation - Insert and Delete Function

In [150]:
help(np.insert)

Help on function insert in module numpy:

insert(arr, obj, values, axis=None)
    Insert values along the given axis before the given indices.
    
    Parameters
    ----------
    arr : array_like
        Input array.
    obj : int, slice or sequence of ints
        Object that defines the index or indices before which `values` is
        inserted.
    
        .. versionadded:: 1.8.0
    
        Support for multiple insertions when `obj` is a single scalar or a
        sequence with one element (similar to calling insert multiple
        times).
    values : array_like
        Values to insert into `arr`. If the type of `values` is different
        from that of `arr`, `values` is converted to the type of `arr`.
        `values` should be shaped so that ``arr[...,obj,...] = values``
        is legal.
    axis : int, optional
        Axis along which to insert `values`.  If `axis` is None then `arr`
        is flattened first.
    
    Returns
    -------
    out : ndarray
        A

In [19]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
np.insert(a,1,10)      #it will insert 10 before index 1 and this will be a copy of array...original array will not change

array([ 1, 10,  2,  3,  4,  5,  6,  7,  8,  9])

In [131]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
# Insert in 1d array

np.insert(a,(1,1),10)     # Insert 10 in repeatition

array([ 1, 10, 10,  2,  3,  4,  5,  6,  7,  8,  9])

In [20]:
np.insert(a,(1,2,4),10)   # Insert 10 at different places in array

array([ 1, 10,  2, 10,  3,  4, 10,  5,  6,  7,  8,  9])

In [146]:
np.insert(a,(1,2,4),25.5)   # Insert float value but it will be convert into interger as per array datatype

array([ 1, 25,  2, 25,  3,  4, 25,  5,  6,  7,  8,  9])

In [137]:
np.insert(a,(1,2,4),(10,20,30))  # Insert different values at different places in array

array([ 1, 10,  2, 20,  3,  4, 30,  5,  6,  7,  8,  9])

In [166]:
# Insert in 2d array
b = np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [145]:
np.insert(b,1,20)    # When axis is none, it will flatten the given array before use

array([ 1, 20,  2,  3,  4,  5,  6,  7,  8,  9])

In [147]:
np.insert(b,1,20,axis=0) 

array([[ 1,  2,  3],
       [20, 20, 20],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [148]:
np.insert(b,1,20,axis=1) 

array([[ 1, 20,  2,  3],
       [ 4, 20,  5,  6],
       [ 7, 20,  8,  9]])

In [149]:
np.insert(b,1,[10,20,30], axis =0) 

array([[ 1,  2,  3],
       [10, 20, 30],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [167]:
np.insert(b,1,(10,20,30), axis =0) 

array([[ 1,  2,  3],
       [10, 20, 30],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [151]:
help(np.append)

Help on function append in module numpy:

append(arr, values, axis=None)
    Append values to the end of an array.
    
    Parameters
    ----------
    arr : array_like
        Values are appended to a copy of this array.
    values : array_like
        These values are appended to a copy of `arr`.  It must be of the
        correct shape (the same shape as `arr`, excluding `axis`).  If
        `axis` is not specified, `values` can be any shape and will be
        flattened before use.
    axis : int, optional
        The axis along which `values` are appended.  If `axis` is not
        given, both `arr` and `values` are flattened before use.
    
    Returns
    -------
    append : ndarray
        A copy of `arr` with `values` appended to `axis`.  Note that
        `append` does not occur in-place: a new array is allocated and
        filled.  If `axis` is None, `out` is a flattened array.
    
    See Also
    --------
    insert : Insert elements into an array.
    delete : Delet

In [152]:
# Append in 1d array   
np.append(a,100)     # it will create copy of array, original will not modify

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 100])

In [153]:
# Append in 2d array
np.append(b,[[10,20,30]])    # if Axis not used, then it will flatten 2d into 1d before use

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 20, 30])

In [154]:
np.append(b,[[10,20,30]],axis=0)   # Axis =0   - When Axis are used then becareful about shape of array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30]])

In [158]:
np.append(b,[[10],[20],[30]],axis=1)  # Axis = 1  - When Axis are used then be careful about shape of array

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 30]])

In [159]:
help(np.delete)

Help on function delete in module numpy:

delete(arr, obj, axis=None)
    Return a new array with sub-arrays along an axis deleted. For a one
    dimensional array, this returns those entries not returned by
    `arr[obj]`.
    
    Parameters
    ----------
    arr : array_like
      Input array.
    obj : slice, int or array of ints
      Indicate indices of sub-arrays to remove along the specified axis.
    axis : int, optional
      The axis along which to delete the subarray defined by `obj`.
      If `axis` is None, `obj` is applied to the flattened array.
    
    Returns
    -------
    out : ndarray
        A copy of `arr` with the elements specified by `obj` removed. Note
        that `delete` does not occur in-place. If `axis` is None, `out` is
        a flattened array.
    
    See Also
    --------
    insert : Insert elements into an array.
    append : Append elements at the end of an array.
    
    Notes
    -----
    Often it is preferable to use a boolean mask. For 

In [162]:
np.delete(a,1)      # it will delete from the copy of array, not from the original array

array([1, 3, 4, 5, 6, 7, 8, 9])

In [163]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [164]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [165]:
np.delete(b,2)   # it will flatten the array first then value at index 2 will be deleted

array([1, 2, 4, 5, 6, 7, 8, 9])

In [167]:
np.delete(b,2,axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [168]:
np.delete(b,2,axis=1)

array([[1, 2],
       [4, 5],
       [7, 8]])

## Linear Algebra       :-                     linalg

In [ ]:
# Inverse of a Matrix
# Power of Matrix
# Solve linear equation
# Find out determinant of Matrix

## Inverse of a Matrix

In [201]:
help(np.linalg.inv)

Help on function inv in module numpy.linalg:

inv(a)
    Compute the (multiplicative) inverse of a matrix.
    
    Given a square matrix `a`, return the matrix `ainv` satisfying
    ``dot(a, ainv) = dot(ainv, a) = eye(a.shape[0])``.
    
    Parameters
    ----------
    a : (..., M, M) array_like
        Matrix to be inverted.
    
    Returns
    -------
    ainv : (..., M, M) ndarray or matrix
        (Multiplicative) inverse of the matrix `a`.
    
    Raises
    ------
    LinAlgError
        If `a` is not square or inversion fails.
    
    Notes
    -----
    
    .. versionadded:: 1.8.0
    
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.
    
    Examples
    --------
    >>> from numpy.linalg import inv
    >>> a = np.array([[1., 2.], [3., 4.]])
    >>> ainv = inv(a)
    >>> np.allclose(np.dot(a, ainv), np.eye(2))
    True
    >>> np.allclose(np.dot(ainv, a), np.eye(2))
    True
    
    If a is a matrix object, then the return value is a 

In [191]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [194]:
b=np.linalg.inv(a)
b

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [198]:
np.dot(a,b)    # Dot product of a Matrix and its Inverse should be equal to Identity Matrix 

# in results, values are close to Identity Matrix. For better results, you can use allclose()

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [200]:
# np.eye(2) will create identity matrix of 2 rows and 2 columns here and return True means values are equal

np.allclose(np.dot(a,b),np.eye(2)) 

True

In [202]:
help(np.allclose)

Help on function allclose in module numpy:

allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
    Returns True if two arrays are element-wise equal within a tolerance.
    
    The tolerance values are positive, typically very small numbers.  The
    relative difference (`rtol` * abs(`b`)) and the absolute difference
    `atol` are added together to compare against the absolute difference
    between `a` and `b`.
    
    NaNs are treated as equal if they are in the same place and if
    ``equal_nan=True``.  Infs are treated as equal if they are in the same
    place and of the same sign in both arrays.
    
    Parameters
    ----------
    a, b : array_like
        Input arrays to compare.
    rtol : float
        The relative tolerance parameter (see Notes).
    atol : float
        The absolute tolerance parameter (see Notes).
    equal_nan : bool
        Whether to compare NaN's as equal.  If True, NaN's in `a` will be
        considered equal to NaN's in `b` in the output a

## Power of Matrix 

In [ ]:
# np.linalg.matrix_power(a,n)     - a is matrix and n is power
# Matrix need to be square matrix
# n can be positive, negative and zero
# if n = 0, then Identity matrix will be result
#if n > 0, Power is computed through repeated matrix squaring and matrix multiplication
# if n < 0, first we will find out inverse of a matrix, then take absoulte value of inverse matrix and then raise the inverse matrix to power n

In [204]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [205]:
#if n> 0
np.linalg.matrix_power(a,2)

array([[ 7, 10],
       [15, 22]])

In [206]:
# check above answer
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [207]:
np.linalg.matrix_power(a,3)

array([[ 37,  54],
       [ 81, 118]])

In [208]:
# if n= 0    - result will be identity matrix
np.linalg.matrix_power(a,0)

array([[1, 0],
       [0, 1]])

In [209]:
# if n < 0 
np.linalg.matrix_power(a,-2)

array([[ 5.5 , -2.5 ],
       [-3.75,  1.75]])

In [211]:
# check inverse of matrix a 
b = np.linalg.inv(a)
b

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [215]:
np.linalg.matrix_power(b,2)   # this is same as above answer

array([[ 5.5 , -2.5 ],
       [-3.75,  1.75]])

In [213]:
np.dot(b,b)     # double check through dot function

array([[ 5.5 , -2.5 ],
       [-3.75,  1.75]])

## Linear Equation

In [ ]:
# 3x + y = 9
# x + 2y = 8
# Find the value of x and y basis given linear equations


In [ ]:
# A x = B
# A is Matrix of coefficient
# x is matrix of unknown variable
# B is the constant values 

In [217]:
# A in above given linear equations
a = np.array([[3,1],[1,2]])
b = np.array([9,8])

np.linalg.solve(a,b)      # return result will be identical to shape of b

array([2., 3.])

In [218]:
# Result ----->   x =2 and y = 3

In [222]:
# 3 equations example
# 6x + 2y - 5z = 13
# 3x + 3y - 2z = 13
# 7x + 5y - 3z = 26

a = np.array([[6,2,-5],[3,3,-2],[7,5,-3]])
b = np.array([13,13,26])

np.linalg.solve(a,b)   # Result [ x =2, y=3, and z= 1 ]

array([2., 3., 1.])

In [223]:
c = np.array([[2,1,3],[1,-1,-1],[3,-2,3]])
d = np.array([-2,-3,-12])

np.linalg.solve(c,d)  

array([-1.,  3., -1.])

## Determinant

In [ ]:
# Determinant is very useful value in linear algebra
# Calculated from digonal elements of a Square matrix

In [225]:
dt = np.array([[1,2],[3,4]])
np.linalg.det(dt)

-2.0000000000000004

In [227]:
round(np.linalg.det(dt))

-2.0

In [231]:
dt1 = np.arange(1,10).reshape(3,3)
dt1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [232]:
np.linalg.det(dt1)

6.66133814775094e-16

In [233]:
round(np.linalg.det(dt1))

0.0

__Conclusion__<br>
Numpy is open source add on module to Python.<br>
- By using NumPy you can __speed up__ your workflow and _interface with other packages_ in the Python ecosystem that use NumPy under the hood.
- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support   Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.
- It provide common __mathematical and numerical routines__ in pre-compiled, fast functions. 
- It provides _basic routines_ for manipulating __large arrays and matrices__ of numeric data.

__Key Features__<br/>
- NumPy arrays have a __fixed size__ decided at the time of creation. _Changing the size of an ndarray will create a new array and delete the original._
- The elements in a NumPy array are all required to be of the __same data type__, and thus will be the same size in memory.
- NumPy arrays facilitate __advanced mathematical__ and other types of __operations__ on large numbers of data.